spring:
  datasource:
    name: primary
    url: jdbc:mysql://localhost:3306/jdbc
    username: jdbc-admin
    password: ${JDBC_ADMIN_PWD}
    hikari:
      pool-name: primary
  secondary-datasource:
    name: secondary
    url: jdbc:mysql://localhost:3306/jdbc2
    username: jdbc-admin
    password: ${JDBC_ADMIN_PWD}
    hikari:
      pool-name: secondary
