CREATE DATABASE if not exists jdbc;
CREATE DATABASE if not exists jdbc2;

CREATE USER if not exists 'jdbc-admin'@'localhost' identified by '';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'jdbc-admin'@'localhost';

GRANT
	ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EXECUTE, GRANT OPTION, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE
ON jdbc.*
TO 'jdbc-admin'@'localhost'
WITH GRANT OPTION;

GRANT
	ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EXECUTE, GRANT OPTION, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE
ON jdbc2.*
TO 'jdbc-admin'@'localhost'
WITH GRANT OPTION;
